CREATE TABLE CLIENTE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR(11)
);

CREATE TABLE PRODUTO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100),
    PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INT REFERENCES CLIENTE(ID),
    DATA_PEDIDO TIMESTAMP,
    STATUS VARCHAR(20),
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEM_PEDIDO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID INT REFERENCES PEDIDO(ID),
    PRODUTO_ID INT REFERENCES PRODUTO(ID),
    QUANTIDADE INT
);

CREATE TABLE USUARIO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(50) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    ADMIN BOOL DEFAULT FALSE
);
